name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  macos:
    name: macOS (Xcode ${{ matrix.xcode }})
    strategy:
      fail-fast: false
      matrix:
        xcode: ["13.4.1", "13.2.1"]
        include:
          - xcode: "13.4.1"
            macos: macOS-12
          - xcode: "13.2.1"
            macos: macOS-11
    runs-on: ${{ matrix.macos }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Tests
        run: swift test
  linux:
    name: Linux (Swift ${{ matrix.swift }})
    strategy:
      fail-fast: false
      matrix:
        swift: ["5.5", "5.6"]
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Tests
        run: swift test

